Дементьев Сергей Андреевич, Б05-205, контест 2, задача D, id: 71265736
sdem3/AlgoMipt pull request #6
Opened 2022-11-02 16:38 UTC by sdem3

2022-11-28 19:33 UTC, orenty7 requested changes

2022-11-28 19:33 UTC, orenty7 commented on task-D.cpp
> +  std::vector<long long> data;
Переменные вперемешку с функциями и к тому же публичные. Вынести наверх или вниз класса  и сделать приватными

2022-11-28 19:33 UTC, orenty7 commented on task-D.cpp
> +  std::cin >> request[0] >> request[1];
request[i] читать очень сложно. По смыслу это разные значение с разным предназначением. Для хранения и передачи коэффициентов последовательности лучше создать структуру типа `struct { int64_t a0, x, y }` и передавать её

2022-11-28 19:33 UTC, orenty7 commented on task-D.cpp
> +  void Insert(long long val) {
long long и int64_t это не всегда одно и то же. Лучше выбрать один тип и везде использовать его. Я бы отдал предпочтение int64_t

2022-12-07 23:17 UTC, VladislavHacker commented
PING!!!

2022-12-07 23:22 UTC, VTroyanGolovyan requested changes
ДЕЛАЙ ПРАВКИ

2022-12-20 20:15 UTC, VladislavHacker commented
я поставлю половинный бал) тоже самое я сделал со всеми кто забил на ревью.

2022-12-20 20:15 UTC, closed without merging